# Generated by Django 5.0.3 on 2024-07-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_question_question_question_to_do_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
