# Generated by Django 5.0.3 on 2024-07-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0004_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='question',
            new_name='to_do',
        ),
    ]
