# Generated by Django 4.2.14 on 2024-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
