# Generated by Django 5.0.3 on 2024-07-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0005_rename_question_checklist_to_do'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='to_do',
            new_name='question',
        ),
    ]
