# Generated by Django 5.0.3 on 2024-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0007_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
