# Generated by Django 4.2.14 on 2024-07-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0007_remove_post_video_url_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
