# Generated by Django 4.2.14 on 2024-07-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0010_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
