# Generated by Django 4.2.14 on 2024-07-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='experts/')),
            ],
        ),
    ]
