# Generated by Django 4.2.14 on 2024-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0015_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_receipt',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_file',
            field=models.ImageField(blank=True, null=True, upload_to='payment/'),
        ),
    ]
