# Generated by Django 4.2.14 on 2024-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0016_remove_payment_bank_receipt_payment_payment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
