# Generated by Django 4.2.14 on 2024-07-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0017_userprofile_birth_date_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
